#pragma once

#ifdef AUDIO_ENABLE
    #define STARTUP_SONG SONG(PLANCK_SOUND)
#endif

#define ENCODER_RESOLUTION 4

#define UNICODE_SELECTED_MODES UC_LNX, UC_OSX

// #define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 300

#define TAPPING_TERM 150
